// Code generated by go generate; DO NOT EDIT.
package main

import (
	"fmt"
	"strconv"
)

type Animal int

const (
	Dog Animal = 0
	Cat Animal = 1
	Bird Animal = 2
)

func (v Animal) Validate() error {
	switch v {
	case Dog:
		return nil
	case Cat:
		return nil
	case Bird:
		return nil
	}
	return fmt.Errorf("invalid animal: %d", v)
}

func (v Animal) String() string {
	switch v {
	case Dog:
		return "Dog"
	case Cat:
		return "Cat"
	case Bird:
		return "Bird"
	}
	return "%!Animal(" + strconv.Itoa(int(v)) + ")"
}
